openapi: 3.0.1
info:
  title: healthplus-backend
  description: My cool app
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Auth Service
    description: Auth Service endpoints
  - name: User Service
    description: User Service endpoints

paths:
  # /auth/signup:
  #   post:
  #     tags:
  #       - Auth Service
  #     requestBody:
  #       content:
  #         application/json:
  #           schema:
  #             $ref: "#/components/schemas/SignUpBody"
  #       required: true
  #     responses:
  #       200:
  #         description: Success
  #         content:
  #           application/json:
  #             schema:
  #               $ref: "#/components/schemas/SignUpResponse"

  /auth/login:
    post:
      tags:
        - Auth Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginBody"
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUpResponse"

  /auth/google-login:
    post:
      tags:
        - Auth Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GoogleLoginBody"
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignUpResponse"

components:
  schemas:
    SignUpResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"

    SignUpBody:
      type: object
      required:
        - name
        - email
        - password
        - phone
        - role
        - dob
        - gender
      properties:
        name:
          type: string
          example: "Raj Varsani"
        email:
          type: string
          format: email
          example: "imt_2020111@iiitm.ac.in"
        password:
          type: string
          example: "password"
        phone:
          type: string
          example: "1234567890"
        role:
          type: string
          enum: ["doctor", "patient", "attendant", "admin"]
          example: "patient"
        dob:
          type: string
          format: date
          example: "2003-07-09"
        gender:
          type: string
          example: "Male"
          enum: ["Male", "Female", "Others"]

    LoginBody:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "johndoe@test.com"
        password:
          type: string
          example: "password"

    GoogleLoginBody:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          example: "4/0AY0e-g5Uq7q3"

    Error:
      type: object
      additionalProperties: true
